/**********************************************************************
 * Extern for MessageFormat
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var MessageFormat = {
    "defaultLocale": {},
    "escape": function () {},
    "formatters": {
        "date": function () {},
        "number": function () {},
        "time": function () {}
    }
};
MessageFormat.prototype = {
    "addFormatters": function () {},
    "compile": function () {},
    "disablePluralKeyChecks": function () {},
    "setBiDiSupport": function () {},
    "setIntlSupport": function () {},
    "setStrictNumberSign": function () {}
};
/**********************************************************************
 * End Generated Extern for MessageFormat
 /**********************************************************************/

